### ISSUE TITLE
Problems with dependencies in latest build

### ISSUE THREAD

**Issue by oyvindln** [ernstp/ppa-mesarc#20]
There seems to be something broken with the latest set of mesa packages in the ppa, the x86-64 seem suddenly be mutualy exclusive with the i386 variants of the same package and can no longer be both installed at the same time which causes problems with other dependencies.

(Using 24.04 Noble I should note, don't know if it's also an issue on jammy.)

EDIT: worked fine in a jammy VM so not gonna say 100% sure that it's not my system that is a bit borky

**Comment by ernstp** [comment]
Ah indeed, the i386 build for noble failed!
I got lost in some other noise... i'm on it :-)

**Comment by oyvindln** [comment]
Awesome - and thanks for the work on the repo

**Comment by oyvindln** [comment]
Seems to have fixed the breakages and now upgrades fine - though graphics now breaks after trying to upgrade to the packages in the ppa nstead on my main system with AMD graphics (with error messages about failing to find gpus / radeonsi libraries etc) - it works fine in a clean Virtualbox VM though so it could be just something with my system.

**Comment by nebadon2025** [comment]
> Seems to have fixed the breakages and now upgrades fine - though graphics now breaks after trying to upgrade to the packages in the ppa nstead on my main system with AMD graphics (with error messages about failing to find gpus / radeonsi libraries etc) - it works fine in a clean Virtualbox VM though so it could be just something with my system.

I am having the exact same problem in Ubuntu 24.04 I had to ppa-purge and go back to stock mesa because this and also Oibafs PPA produce the same results, complete breakage on my 6800XT machine.  Interestingly I have a Fedora 40 machine I am testing NVK on a RTX 3090 with on mesa-git also and it is also completely broken right now, not sure what is going on but none of my machines work on mesa-git anymore or this unstable PPA.

**Comment by nebadon2025** [comment]
ok so I just tested this PPA again and it is alive and well, thanks @ernstp !
